//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticatingManager
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class User
    {
        public User()
        {
        }
        public User(string id,string username,string password)
        {
            this.Id = id;
            this.Username = username;
            this.Password = password;
        }

        public string Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
